import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <Link class="navbar-brand" href='/'>Home</Link>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <Link class="nav-link active" aria-current="page" href='/pages/Reserva'>Reservas</Link>
        </li>
        <li class="nav-item">
          <Link class="nav-link" href='/pages/Contacto'>Contacto</Link>
        </li>
        <li class="nav-item">
          <Link class="nav-link" href='/pages/Nosotros'>Sobre Nosotros</Link>
        </li>
       
      </ul>
      <span class="navbar-text">
      </span>
    </div>
  </div>
</nav>
<div>
{children}
</div>
      </body>
    </html>
  );
}
